name: Enter_your_address
run-name: Your address is inside
on: 
  workflow_dispatch:
   inputs:
      name:
        description: Enter your sweet name
        default: ''
        required: true
jobs:
  display_files:
    name: Your address is 
    runs-on: ubuntu-latest
    steps:        
    - name: display output
      run: |
          echo ${{ inputs.name }}
      shell: bash
