name: Enter_your_address
run-name: check-access-control | subject area [${{ inputs.subjectarea }}]
on: 
  workflow_dispatch:
jobs:
  display_files:
    name: Your address is 
    runs-on: ubuntu-latest
    steps:        
    - name: display output
      run: |
          echo "Bangalore"
      shell: bash
