name: Enter_your_address
on: workflow_dispatch:
jobs:
  display_files:
    name: Your address is 
    runs-on: ubuntu-latest
    steps:        
    - name: display output
      run: |
          echo "Bangalore"
      shell: bash
