name: Enter_your_address
run-name: Your address is inside
on: 
  workflow_dispatch:
   inputs:
      name:
        description: Enter your sweet name
        default: ''
        required: true
      city:
        description: Enter your city
        default: ''
        required: true
      pin:
        description: Enter your City PIN
        default: ''
        required: true
jobs:
  display_files:
    name: Your address is 
    runs-on: ubuntu-latest
    steps:        
    - name: display output
      run: |
          echo Yourname: ${{ inputs.name }} Your_city: ${{ inputs.city }} Your_city_PIN: ${{ inputs.pin }}
      shell: bash
