name: My first code

on: workflow_dispatch

jobs:
  display_my_code:
    name: My code output
    runs-on: ubuntu-latest
    steps:        
    - name: display output
      run: |
          echo " This is my first code"
