name: abc - check access control
run-name: check-access-control | subject area [${{ inputs.subjectarea }}]
on:
  workflow_dispatch:
    inputs:
      subjectarea:
        description: Subject Area (3-Letter)
        default: ''
        required: true

jobs:
  check-access-dev:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'This is test statement'

          
