name: Print my address
#run-name: Print my address | ${{ inputs.your_name }} | ${{ inputs.your_name }}
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  
